version: "3"
services:

  api:
    build: .
    image: swissartresearx/sari-iiif-manifest-service:1.0.0
    container_name: ${PROJECT_NAME}_api
    restart: unless-stopped
    environment:
      - CONFIG_YML=${CONFIG_YML}
      - SPARQL_ENDPOINT=${SPARQL_ENDPOINT}
    networks:
      - default
    volumes:
      - ./config:/config

networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true