services:

  api:
    build: .
    image: swissartresearx/sari-iiif-manifest-service:1.2.0
    container_name: ${PROJECT_NAME}_api
    restart: unless-stopped
    environment:
      - CONFIG_YML=${CONFIG_YML}
      - SPARQL_ENDPOINT=${SPARQL_ENDPOINT}
      - SPARQL_HTTP_AUTH=${SPARQL_HTTP_AUTH}
      - SPARQL_USERNAME=${SPARQL_USERNAME}
      - SPARQL_PASSWORD=${SPARQL_PASSWORD}
      - SPARQL_BEARER_TOKEN=${SPARQL_BEARER_TOKEN}
      - SPARQL_TIMEOUT=${SPARQL_TIMEOUT}
      - SPARQL_REQUEST_METHOD=${SPARQL_REQUEST_METHOD}
    networks:
      - default
    volumes:
      - ./cache:/cache
      - ./config:/config

networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true