version: "3"
services:

  api:
    build: ./services/api
    container_name: ${PROJECT_NAME}_api
    restart: unless-stopped
    environment:
      - FIELD_DEFINITIONS_YML=${FIELD_DEFINITIONS_YML}
      - NAMESPACE=${NAMESPACE}
      - HOST_LOCATION=${HOST_NAME}
      - SPARQL_ENDPOINT=${SPARQL_ENDPOINT}
    networks:
      - default
    volumes:
      - ./config:/config

networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true